version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_PASSWORD}   # establece la contraseña de root
      MYSQL_DATABASE: ${DATABASE_MYSQL_DATABASE}     # crea una base de datos con este nombre
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mmysql
    env_file:
      - .env

volumes:
  db_data: